Первая версия 7 ТЗ
rossanatotolo/java-kanban pull request #2
Opened 2024-05-28 16:26 UTC by rossanatotolo

2024-05-29 19:21 UTC, Fleaman777 requested changes

2024-05-29 19:21 UTC, Fleaman777 commented on src/service/FileBackedTaskManager.java
> +public class FileBackedTaskManager extends InMemoryTaskManager implements TaskManager {
можно не имплементировать TaskManager, тк он уже есть в InMemoryTaskManager

2024-05-29 19:21 UTC, Fleaman777 commented on src/service/FileBackedTaskManager.java
> +                if (str[1].equals(TypeTask.TASK.toString())) {
str[1] - можно вынести в локальную переменную для лучшего восприятия

2024-05-29 19:21 UTC, Fleaman777 commented on src/service/FileBackedTaskManager.java
> +            throw new ManagerSaveException("Произошла ошибка" + e.getMessage());
"Произошла ошибка " - можно пробел поставить)

2024-05-29 19:56 UTC, rossanatotolo commented on src/service/FileBackedTaskManager.java
> +                if (str[1].equals(TypeTask.TASK.toString())) {
Все замечания исправила, спасибо за ревью))

2024-05-30 14:47 UTC, Fleaman777 approved these changes

2024-06-06 18:48 UTC, merged