Первая версия 8ТЗ
rossanatotolo/java-kanban pull request #3
Opened 2024-06-10 14:01 UTC by rossanatotolo

2024-06-11 15:02 UTC, Fleaman777 requested changes

2024-06-11 15:02 UTC, Fleaman777 commented on src/service/FileBackedTaskManager.java
> +        epics.values().stream().map(this::toStringConvert).forEach(allTasks::add);
стрим можно собрать из нескольких списков, поробуй так оптимизировать код

2024-06-11 15:02 UTC, Fleaman777 commented on src/service/FileBackedTaskManager.java
> +            optional.ifPresentOrElse(
можно как бы не прерывая стрим, дальше как нам. необходимо обработать Optional и в итоге получить уже реальное значение без Optional обертки

2024-06-11 15:02 UTC, Fleaman777 commented on src/service/InMemoryTaskManager.java
> +    TreeSet<Task> prioritizedTasks = new TreeSet<>(Comparator.comparing(Task::getStartTime));
так же хорошо было бы повесить подходящий модификатор доступа

2024-06-11 15:02 UTC, Fleaman777 commented on src/service/InMemoryTaskManager.java
> +    public boolean checkTaskTime(Task task) {
метод хороший, но из названия не очень понятно, в каком случае он может быть true, а в каком false

2024-06-11 15:02 UTC, Fleaman777 commented on src/service/InMemoryTaskManager.java
> +                .filter(task -> task.getStartTime() != null)
как альтернативный вариант проверять объект на null использовать Objects.nonNull(..)

2024-06-11 15:02 UTC, Fleaman777 commented on src/service/InMemoryTaskManager.java
> +        optional.ifPresent(epic::setStartTime);
аналагично похожему моменту выше

2024-06-11 15:02 UTC, Fleaman777 commented on test/service/FileBackedTaskManagerTest.java
> +    public void shouldTimeTest() {
тут из названия тоже не очень понятно. что за время такое должно быть у задачи

2024-06-12 10:34 UTC, rossanatotolo commented on src/service/InMemoryTaskManager.java
> +                .filter(task -> task.getStartTime() != null)
сделала))

2024-06-13 06:06 UTC, Fleaman777 approved these changes

2024-06-13 06:06 UTC, Fleaman777 commented on src/service/FileBackedTaskManager.java
> +                .collect(Collectors.toList());
супер, то, что нужно

2024-06-13 06:06 UTC, Fleaman777 commented on src/service/InMemoryTaskManager.java
> +    public boolean isTaskOverlap(Task task) {
👍

2024-06-18 09:02 UTC, merged