Первая версия ТЗ9
rossanatotolo/java-kanban pull request #4
Opened 2024-06-21 23:06 UTC by rossanatotolo

2024-06-21 23:13 UTC, rossanatotolo commented
Привет))Задание было необъятное, могла что-то упустить или продублировать код, но очень старалась быть внимательной и краткой))

2024-06-22 21:13 UTC, Fleaman777 requested changes

2024-06-22 21:13 UTC, Fleaman777 commented on src/adapter/LocalDateTimeAdapter.java
> +    private final DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd.MM.yyyy HH:mm");
в принципе из этого можно сделать константу, что бы в каждом экземпляре LocalDateTimeAdapter не создавалась новая неизменная переменная, а была общая на все

2024-06-22 21:13 UTC, Fleaman777 commented on src/handler/BaseHttpHandler.java
> +    }
хороший общий метод

2024-06-22 21:13 UTC, Fleaman777 commented on src/handler/BaseHttpHandler.java
> +    }
общую часть методов send можно было бы так же вынести в общий приватный метод

2024-06-22 21:13 UTC, Fleaman777 commented on src/handler/EpicHandler.java
> +                sendNotFound(httpExchange, e.getMessage());
в теории в методе taskManager.getEpic(postId.get()) может вылететь какое-то другое исключение никак не связанное с тем, что эпик не найден, а наш сервер вернет ответ как будто ошибка именно в этом, что может немного сбить с толку клиента

2024-06-22 21:13 UTC, Fleaman777 commented on src/handler/EpicHandler.java
> +            } catch (Exception e) {
вот здесь хорошая обработка

2024-06-22 21:13 UTC, Fleaman777 commented on src/handler/SubTaskHandler.java
> +            case "DELETE":
так и напрашиваются эти константы DELETE GET POST вынести в отдельное общее место, как насчет BaseHttpHandler

2024-06-22 21:13 UTC, Fleaman777 commented on src/http/HttpTaskServer.java
> +}
не увидел изменения в Managers классе согласно ТЗ

2024-06-22 21:13 UTC, Fleaman777 commented on test/handler/SubTaskHandlerTest.java
> +}
тесты хорошие, мне нравятся, 
практически без дублирования))

2024-06-24 09:30 UTC, rossanatotolo commented on src/handler/EpicHandler.java
> +                sendNotFound(httpExchange, e.getMessage());
упустила этот момент, исправила))

2024-06-24 13:21 UTC, rossanatotolo commented on src/handler/SubTaskHandler.java
> +            case "DELETE":
вынесла в отдельный класс, чтобы не в полях висели, думала еще через перечисление сделать enum, но в итоге так)) надеюсь, то, что надо))

2024-06-25 05:52 UTC, Fleaman777 approved these changes

2024-06-28 14:10 UTC, merged